### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Alvyre** [Arctic76/QuickShare#1]
# **Front :**
- [x] Sign-up view
- [x] Sign-in view
- [x] User profile view
- [x] Add information view
- [x] info view ( + edit )
- [x] Store the token in localdata & logout function
- [x] Contact & About view
- [x] change all links to the API with a config file
- [x] Basic Filters
- [x] Profile of other users
- [x] Comment the code
- [x] Implement comments
- [x] Implement web push notifications
- [x] Clean the code
- [ ] Optimize the code

## **Back:**
- [x] Finish routes
- [x] Secure the API (token)
- [x] Add a upvote/downvote system for the posts and events
- [x] Delete script (Kōtotsu)
- [x] Add Socket.io
- [x] BONUS install HTTPS
- [x] Comment the code
- [x] Add comments feature
- [x] Add web push notifications
- [x] Clean code
- [ ] Optimize the code

## **Optionnal**

- [x] Support QRCode to addinfo view (location auto filled up)
- [ ] Add stats manager
- [ ] Interactive map
- [ ] Filter by zones
- [ ] Write a Wiki (WIP)
- [ ] Update Recaptcha to Invisible Recaptcha
